# type:ignore
"""init table define

Revision ID: 86ec05d3b672
Revises:
Create Date: 2020-12-12 18:48:04.438054

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86ec05d3b672"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group", sa.Integer(), nullable=True),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("privilege", sa.String(length=255), nullable=False),
        sa.Column("data", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_ix_feature_data_unique",
        "feature_data",
        ["group", "user", "privilege"],
        unique=True,
    )
    op.create_index(
        op.f("ix_feature_data_group"), "feature_data", ["group"], unique=False
    )
    op.create_index(
        op.f("ix_feature_data_privilege"), "feature_data", ["privilege"], unique=False
    )
    op.create_index(
        op.f("ix_feature_data_user"), "feature_data", ["user"], unique=False
    )
    op.create_table(
        "feature_privileges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group", sa.Integer(), nullable=True),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("privilege", sa.String(length=255), nullable=False),
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_ix_feature_privileges_unique",
        "feature_privileges",
        ["group", "user", "privilege"],
        unique=True,
    )
    op.create_index(
        op.f("ix_feature_privileges_group"),
        "feature_privileges",
        ["group"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_privileges_privilege"),
        "feature_privileges",
        ["privilege"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_privileges_user"), "feature_privileges", ["user"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feature_privileges_user"), table_name="feature_privileges")
    op.drop_index(
        op.f("ix_feature_privileges_privilege"), table_name="feature_privileges"
    )
    op.drop_index(op.f("ix_feature_privileges_group"), table_name="feature_privileges")
    op.drop_index("_ix_feature_privileges_unique", table_name="feature_privileges")
    op.drop_table("feature_privileges")
    op.drop_index(op.f("ix_feature_data_user"), table_name="feature_data")
    op.drop_index(op.f("ix_feature_data_privilege"), table_name="feature_data")
    op.drop_index(op.f("ix_feature_data_group"), table_name="feature_data")
    op.drop_index("_ix_feature_data_unique", table_name="feature_data")
    op.drop_table("feature_data")
    # ### end Alembic commands ###
